
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPTION = 19;
  public static final int SEMICOLON = 10;
  public static final int QUOTES = 23;
  public static final int UPPERC = 14;
  public static final int IDENTIFIER = 7;
  public static final int CONCAT = 18;
  public static final int GREATER = 9;
  public static final int SEPARATOR = 3;
  public static final int LBRACKET = 2;
  public static final int COLON = 6;
  public static final int RBRACKET = 4;
  public static final int TILDE = 11;
  public static final int KLEENE = 21;
  public static final int STRING = 25;
  public static final int LOWERC = 13;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int CONJ = 5;
  public static final int UNION = 17;
  public static final int HYPHEN = 8;
  public static final int NEWLINE = 22;
  public static final int error = 1;
  public static final int ITERATION = 20;
  public static final int ASCII = 16;
  public static final int APOSTROPHE = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACKET",
  "SEPARATOR",
  "RBRACKET",
  "CONJ",
  "COLON",
  "IDENTIFIER",
  "HYPHEN",
  "GREATER",
  "SEMICOLON",
  "TILDE",
  "COMMA",
  "LOWERC",
  "UPPERC",
  "NUMBER",
  "ASCII",
  "UNION",
  "CONCAT",
  "OPTION",
  "ITERATION",
  "KLEENE",
  "NEWLINE",
  "QUOTES",
  "APOSTROPHE",
  "STRING"
  };
}

